name: Docker Push
on:
  push:
    tags:
      - '**'

jobs:
  docker-push:
    name: Docker push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login to DockerHub
        if: needs.semantic-release.outputs.new_release_published == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        if: needs.semantic-release.outputs.new_release_published == 'true'
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        if: needs.semantic-release.outputs.new_release_published == 'true'
        uses: docker/setup-buildx-action@v3
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          labels: |
            org.opencontainers.image.url=https://hub.docker.com/r/rubencabrera/odoo-base-image
          images: rubencabrera/odoo-base-image
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
      - name: Docker build and push
        if: needs.semantic-release.outputs.new_release_published == 'true'
        id: docker_push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
